name: 'Setup build tools'
description: 'Configures build variables, installs specific JDK version, and prepares for Gradle tasks'

inputs:
  basis-theory-api-url:
    description: 'The Basis Theory API URL used within the example app'
    required: true
  basis-theory-api-key:
    description: 'The Basis Theory API key used within the example app'
    required: true

runs:
  using: "composite"
  steps:
    - name: Write local.properties file
      run: |
        echo BASIS_THEORY_API_URL=\"${{ inputs.basis-theory-api-url }}\" > ./local.properties
        echo BASIS_THEORY_API_KEY=\"${{ inputs.basis-theory-api-key }}\" >> ./local.properties

    - name: Setup JDK version
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'gradle'

    - name: Setup Gradle cache
      uses: gradle/gradle-build-action@v2