name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write local.properties file
        run: |
          echo BASIS_THEORY_API_URL=\"https://api-dev.basistheory.com\" > ./local.properties
          echo BASIS_THEORY_API_KEY=\"${{ secrets.BASIS_THEORY_API_KEY }}\" >> ./local.properties

      - name: Setup JDK version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Setup AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          target: default
          arch: x86_64
          profile: pixel_3a
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          target: default
          arch: x86_64
          profile: pixel_3a
          script: ./gradlew connectedCheck